version: "2.1"
services:
  web:
    container_name: bookings_app
    image: bookings
    build: ./
    depends_on:
      database:
        condition: service_healthy
    ports: 
      - "3010:3000"
  database:
    container_name: localhost2
    image: mysql:5.7
    environment:
      MYSQL_HOST: "host.docker.internal"
      MYSQL_USER: "jb"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: bookings
    volumes:
      - ./server/db/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./server/db/2-dump.sql:/docker-entrypoint-initdb.d/2-dump.sql
      - ./server/db/3-permissions.sql:/docker-entrypoint-initdb.d/3-permissions.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 3
    ports:
      - "3307:3306"