CREATE USER 'jb'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'jb'@'localhost' WITH GRANT OPTION;
CREATE USER 'jb'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'jb'@'%' WITH GRANT OPTION;
CREATE USER 'jb'@'127.0.0.1' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'jb'@'127.0.0.1' WITH GRANT OPTION;
CREATE USER 'jb'@'172.17.0.3' IDENTIFIED BY 'password';